region_name     = "us-west-1"
org_name        = "starfleet"
department_name = "bridge"
solution_name   = "cxp-starfleet"
solution_stage  = "production"
solution_fqn    = "cxp-starfleet"
network_name    = "public"
network_cidr    = "10.47.0.0/16"