apiVersion: apps/v1
kind: Deployment
metadata:
  name: starship-registry-deployment
  labels:
    app.kubernetes.io/name: starship-registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: starship-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: starship-registry
    spec:
      containers:
      - name: starship-registry
        image: docker.cloudtrain.aws.msgoat.eu/cxp/starfleet/registry-number:1.0.0-csharp
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
