apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: cxp-team-starfleet-ingress
  labels:
    name: starship-registry
spec:
  ingressClassName: nginx
  rules:
  - host: cxp.k8s.azure.msgoat.eu
    http:
      paths:
      - pathType: Prefix
        path: "/cxp-team-starfleet/starship-registry(/|$)(.*)"
        backend:
          service:
            name: starship-registry-service
            port:
              name: http
