apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starship-registry-ingress
  labels:
    name: starship-registry
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/starfleet"
        backend:
          service:
            name: starfleet-registry
            port:
              number: 80
