apiVersion: v1
kind: Service
metadata:
  name: starship-registry-service
  labels:
    app.kubernetes.io/name: starship-registry
spec:
  selector:
    app.kubernetes.io/name: starship-registry
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
