apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ETXlOREV3TURnME4xb1hEVE16TURNeU1URXdNRGcwTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTklFClNqdWx1Wlp2VlpPeEVwU2FyMnNnR2pxOU9OTHNvSlIyaEo3UG1yUzFqTjNtVW9SKzVPMTRBUzJUU3NBT2N1OXUKY0xvbmE5OE51TDUwRE5EeGI3ZjRMTmd2bERrWC9BTVdwSDNRbTcxN3J1NFllSnRFQU5VQ0k4UmNURXZrTWlCdgpVUmwrTHdmS1JJOHZGZ0FyelpSTEcrbGQyQUdBWlBSTFFZcExiRDRLSWRVYkxhUExwVGxDMlVPRHo3SFlyM05lCnNzOExNRkQrOGNSNGhxU3NJWStxN0VWM1dzNEtURXZQR2s2ZVlCd2ovbzRoaEtoaVJoQk1Wc0drRWJ4bW5HakYKRW9Na3Z1aDd1NHlrQVE5N1hwNkk3TEZ5R1dVU1VaMUROM1RPdGRKalNyM0ZxVEZUWFREdFlUZDhmem1mc0cxMgpTWDZsTGo1NHo1RHN2VDhlOFJNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMQ1JUUHc2MXZReit5SWdUS09JRnNYY0E4ZVJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVN6c21MWldPeGw0Q2RLdW5sNwp4OVg5MERZWHdnZXh3Snc5clFoY01QWi9QcTZyRCtMZzhNL0dqMDdwOVNlWlZ4V3hnNTVDOXFYMW9uNkR3emVGCkMyNCtLWUorVmwvdEVaNUVrbmlhdjNyaXpaS3VXNHJyQ0Jsb3Z3eFBKNzFveVAxSCt2bzVIeVloRXIrWHA2eEcKUHFHdnNjRlNOQm9lczVqVFR6NHZ1MTk2ZVNWcjUwYUZzM09oa3ZJVjVacy9zUVZLTEFMY0VQdEdxUUZBbENtNQpwN1lTVHhab2xzckR2a05Hd2U0Y1FTWFhIaWpINUd4N0tYTGZmcGZJQll4VlVCWWYrYlFhNEZhcTFKWWRHbzd6Cmc3bWQ4eExHaldvQkppeU1QN2UwQlFieTNoWkRlajlUcjFHRnVxSG9qUU5mR3hGMGwycER1eTExWG9Ma0JLSU4KSnJVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://83CE361B5EADF082CB38020FB21263F8.sk1.us-west-1.eks.amazonaws.com
  name: arn:aws:eks:us-west-1:005913962162:cluster/starfleet-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-west-1:005913962162:cluster/starfleet-eks-cluster
    user: arn:aws:eks:us-west-1:005913962162:cluster/starfleet-eks-cluster
  name: arn:aws:eks:us-west-1:005913962162:cluster/starfleet-eks-cluster
current-context: arn:aws:eks:us-west-1:005913962162:cluster/starfleet-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-1:005913962162:cluster/starfleet-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-1
      - eks
      - get-token
      - --cluster-name
      - starfleet-eks-cluster
      command: aws
      env:
      - name: AWS_PROFILE
        value: cxp-heinleim-sts
