region_name      = "us-west-1"
org_name         = "msg"
department_name  = "BrAM"
solution_name    = "cxp"
solution_stage   = "production"
solution_fqn     = "starfleet"
network_name     = "public"
network_cidr     = "10.47.0.0/16"